### ISSUE TITLE
Download Urls not working

### ISSUE THREAD

**Issue by theonlyremedy** [KyloIO/kylo-docs#33]
Hello Kylo Team, none of the download links are working, could you guys please check and correct if possible?

Ex. When I try to access : http://bit.ly/2BXUXtI (https://s3-us-west-2.amazonaws.com/kylo-io/releases/rpm/0.10.1/kylo-0.10.1.rpm), I get
`<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>A031D6F187FA0084</RequestId><HostId>e0R2qwcFTE3iIFJOmSZOXoDNu+icDM50Cz+LHzIvf5IQDT3u5BiJddfkeS0GVWXoHzw0Y9sb1cg=</HostId></Error>`

**Comment by ganesh-gonnuru** [comment]
@theonlyremedy  I'm also facing the same issue , please share any solution if found....!

**Comment by 20100507** [comment]
Hello Kylo Team, when I download tar file,I can not download it. so I compile it myself. the following error:

```
[ERROR] module.js:472
[ERROR]     throw err;
[ERROR]     ^
[ERROR] 
[ERROR] Error: Cannot find module '/home/hadoop/kylo-0.10.1/ui/ui-app/node_modules/@uirouter/core/migrate/migratewarn.js'
[ERROR]     at Function.Module._resolveFilename (module.js:470:15)
[ERROR]     at Function.Module._load (module.js:418:25)
[ERROR]     at Module.runMain (module.js:605:10)
[ERROR]     at run (bootstrap_node.js:427:7)
[ERROR]     at startup (bootstrap_node.js:151:9)
[ERROR]     at bootstrap_node.js:542:3
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[ERROR] 
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! @uirouter/core@5.0.17 install: `node migrate/migratewarn.js`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the @uirouter/core@5.0.17 install script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```
please tell how can I resolve! thanks~ and **Download Urls not working**

**Comment by brahmovacha** [comment]
Same here, Issue still persists. I am using with DEB with no luck so far..
Any help here would be highly appreciated.

--2020-07-09 19:44:04--  http://bit.ly/2FQLPeM
Resolving bit.ly (bit.ly)... 67.199.248.11, 67.199.248.10
Connecting to bit.ly (bit.ly)|67.199.248.11|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://s3-us-west-2.amazonaws.com/kylo-io/releases/deb/0.10.0/kylo-0.10.0.deb [following]
--2020-07-09 19:44:11--  https://s3-us-west-2.amazonaws.com/kylo-io/releases/deb/0.10.0/kylo-0.10.0.deb
Resolving s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)... 52.218.224.112
Connecting to s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)|52.218.224.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-07-09 19:44:16 ERROR 404: Not Found.

**Comment by ASHISHTOM** [comment]
It is still same for me. Not able to download

**Comment by imrajsinghsandhu** [comment]
same for me, still unable to download
